- name: "Creates backend app directory"
  file:
    path: ~/backend-app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-app

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend-app
    npm i

- name: 'install pm2'
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes

- name: 'start application'
  become: yes
  shell: |
    pm2 save
    pm2 startup

    pm2 start npm -- start
